//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTraderDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TDAKey> TDAKeys { get; set; }
        public virtual DbSet<AlpacaSetting> AlpacaSettings { get; set; }
        public virtual DbSet<HistoricalLog> HistoricalLogs { get; set; }
        public virtual DbSet<HistoricalOHLC> HistoricalOHLCs { get; set; }
    }
}
