//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTraderDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlpacaSetting
    {
        public int Id { get; set; }
        public string API_KEY { get; set; }
        public string API_SECRET { get; set; }
        public string API_URL { get; set; }
        public Nullable<bool> PAPER_TRADING { get; set; }
    }
}
