//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTraderDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalOHLC
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> Close { get; set; }
        public Nullable<decimal> High { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<long> Volume { get; set; }
        public Nullable<System.DateTime> Timeframe { get; set; }
        public Nullable<int> Timespan { get; set; }
    }
}
