//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTraderDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalTransaction
    {
        public int Id { get; set; }
        public string side { get; set; }
        public string type { get; set; }
        public string alpacaID { get; set; }
        public string symbol { get; set; }
        public Nullable<decimal> actualPrice { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> dollarquantity { get; set; }
        public Nullable<System.DateTime> transactionDT { get; set; }
    }
}
