//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTraderDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDAKey
    {
        public int id { get; set; }
        public System.DateTime last_update { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public Nullable<int> access_expires { get; set; }
        public Nullable<int> refresh_expires { get; set; }
        public string scope { get; set; }
        public string consumerKey { get; set; }
        public string callbackURL { get; set; }
        public string UserName { get; set; }
        public string decodedKey { get; set; }
        public string encodedKeyURL { get; set; }
        public string accessTokenURL { get; set; }
    }
}
